// Generated by CoffeeScript 1.6.2
var Handlers;

Handlers = (function() {
  function Handlers() {}

  Handlers.prototype.save = function() {};

  Handlers.prototype.read = function() {};

  return Handlers;

})();

module.exports = Handlers;
