// Generated by CoffeeScript 1.6.2
var Memcached, app, exports, memcached;

Memcached = require('memcached');

app = require('./app');

memcached = exports = module.exports = new Memcached(app.settings.memcached.split(','), {
  retries: 10,
  retry: 10000,
  remove: true
});
