// Generated by CoffeeScript 1.6.2
var app, exports;

app = require('./app');

exports = module.exports = function(req, res, next) {
  var uid;

  uid = req.query.uid;
  if (uid != null) {
    req.uid = uid;
    return next();
  } else {
    return res.send(403);
  }
};
