// Generated by CoffeeScript 1.3.3
var app, memcached;

memcached = require('./memcached');

app = require('./app');

module.exports = function(uid, version, callback) {
  var data, key, memuid;
  memuid = escape(uid);
  key = "" + app.settings.memcachedPrefix + memuid;
  data = {
    version: version
  };
  return memcached.set(key, data, 0, function(err, result) {
    return memcached.gets(key, function(err, result) {
      if (err) {
        return callback(503);
      } else {
        return memcached.cas(key, data, result.cas, 0, function(err, result) {
          if (err) {
            return callback(503);
          } else {
            return callback(200);
          }
        });
      }
    });
  });
};
