// Generated by CoffeeScript 1.3.3
var app, memcached;

memcached = require('./memcached');

app = require('./app');

module.exports = function(uid, version, callback) {
  var data, key1, key2, memuid;
  key1 = "" + app.settings.memcachedPrefix + uid;
  memuid = escape(uid);
  key2 = "" + app.settings.memcachedPrefix + memuid;
  data = {
    version: version
  };
  memcached.set(key1, data, 0, function(err, result) {
    return memcached.gets(key1, function(err, result) {
      if (err) {
        return callback(503);
      } else {
        return memcached.cas(key1, data, result.cas, 0, function(err, result) {
          if (err) {
            return callback(503);
          } else {
            return callback(200);
          }
        });
      }
    });
  });
  return memcached.set(key2, data, 0, function(err, result) {
    return memcached.gets(key2, function(err, result) {
      if (err) {
        return callback(503);
      } else {
        return memcached.cas(key2, data, result.cas, 0, function(err, result) {
          if (err) {
            return callback(503);
          } else {
            return callback(200);
          }
        });
      }
    });
  });
};
